[build]
publish = "public"
command = "npm run build"

[build.environment]
NODE_VERSION = "14"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  skipPatterns = [
    "*.js.map",
    "sw.js",
    "https://www.jamstack.org/slack",
    "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/"
  ]
  checkExternal = true
